### ISSUE TITLE
Clean up compilation/linking warnings

### ISSUE THREAD

**Issue by yying** [trailofbits/osquery#16]
There is quite a bit of warnings during compilation and linking. Ideally, we would like to suppress the ones that are unimportant and fix the ones that are important.

**Comment by artemdinaburg** [comment]
Warnings like `  osquery.lib(config.obj) : warning LNK4217: locally defined symbol ?FLAGS_pack_delimiter@fLS@osquery@@3AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@EA (class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > & osquery::fLS::FLAGS_pack_del
imiter) imported in function "public: bool __cdecl <lambda_00ec61f705cac4d02ced8acdfb10792b>::operator()(class std::shared_ptr<class osquery::Pack> &)const " (??R<lambda_00ec61f705cac4d02ced8acdfb10792b>@@QEBA_NAEAV?$shared_ptr@VPack@osquery@@@std@@@Z) [C:\git\osquery\build\windows10\osquer
y\shell.vcxproj]` are caused by using __declspec(dllimport) on symbols defined in a static library.

When building as static libraries, gflags (and rocksdb) should not define __declspec(dllimport)
